[build]
buildCommand = "npm install --include=dev && npx prisma generate"

[deploy]
startCommand = "node src/server.js"
preDeployCommand = "npx prisma db push --skip-generate"
healthcheckPath = "/health"
